# Generated by Django 5.2 on 2025-05-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_gpasemester_coursegrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1),
        ),
    ]
