# Generated by Django 5.2 on 2025-05-12 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_liveclass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveclass',
            old_name='date',
            new_name='scheduled_at',
        ),
        migrations.AddField(
            model_name='liveclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='meet_link',
            field=models.URLField(default=0.00020576131687242798),
            preserve_default=False,
        ),
    ]
