# Generated by Django 5.2 on 2025-05-12 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_date_liveclass_scheduled_at_liveclass_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='meet_link',
            field=models.URLField(validators=[django.core.validators.RegexValidator(message='Enter a valid Google Meet link (e.g., https://meet.google.com/abc-defg-hij)', regex='^https://meet\\.google\\.com/[a-z]{3}-[a-z]{4}-[a-z]{3}$')]),
        ),
    ]
