# Generated by Django 5.2 on 2025-04-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('JAMB', 'JAMB')], max_length=10)),
                ('year', models.PositiveBigIntegerField()),
                ('question_type', models.CharField(choices=[('CBT', 'Computer Based Test'), ('THEORY', 'Theory')], max_length=10)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(blank=True, max_length=255, null=True)),
                ('option_b', models.CharField(blank=True, max_length=255, null=True)),
                ('option_c', models.CharField(blank=True, max_length=255, null=True)),
                ('option_d', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_option', models.CharField(blank=True, max_length=1, null=True)),
                ('theory_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
