# Generated by Django 5.2 on 2025-04-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_coursematerial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_type',
            field=models.CharField(choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('JAMB', 'JAMB'), ('multile_choice', 'Multiple Choice')], max_length=50),
        ),
    ]
