# Generated by Django 5.2 on 2025-04-28 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_courseexam_coursequestion_courseanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theoryanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='theorysubmission',
            name='question',
        ),
        migrations.RemoveField(
            model_name='theoryanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='theorysubmission',
            name='user',
        ),
        migrations.AlterField(
            model_name='course',
            name='exam_type',
            field=models.CharField(choices=[('FIRST_SEMESTER', 'FIRST SEMESTER'), ('SECOND_SEMESTER', 'SECOND SEMESTER'), ('CA_TEST', 'CA_TEST')], max_length=50),
        ),
        migrations.CreateModel(
            name='CourseExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('correct_answers', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.courseexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CBTAnswer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='TheoryAnswer',
        ),
        migrations.DeleteModel(
            name='TheorySubmission',
        ),
    ]
