# Generated by Django 5.2 on 2025-05-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_examsubmission_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexamattempt',
            name='correct_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseexamattempt',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseexamattempt',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
