# Generated by Django 5.2 on 2025-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_alter_courseexamattempt_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexamattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
